# 2. Тензоры tf.constant и tf.Variable. Индексирование и изменение формы

In [1]:
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf
import numpy as np

2024-09-29 22:24:58.860847: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-29 22:24:58.990054: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-29 22:24:59.024059: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [2]:
print(tf.executing_eagerly())

True


In [3]:
a = tf.constant(1) #число - скаляр
print(a)

tf.Tensor(1, shape=(), dtype=int32)


In [4]:
a = tf.constant(1, shape=(1, 1)) #матрица
print(a)

tf.Tensor([[1]], shape=(1, 1), dtype=int32)


In [5]:
b = tf.constant([1, 2, 3, 4])
print(b)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [6]:
c = tf.constant([[1, 2],
                [3, 4], 
                [5, 6]], dtype = tf.float16)

print(c)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


2024-09-29 22:25:01.505449: E tensorflow/core/util/util.cc:131] oneDNN supports DT_HALF only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.


In [7]:
a2 = tf.cast(a, dtype=tf.float32) #изменение типа данных
print(a2)

tf.Tensor([[1.]], shape=(1, 1), dtype=float32)


In [8]:
b1 = np.array(b) #преобразование тензора в массив Numpy
print(b1)

[1 2 3 4]


In [9]:
b2 = b.numpy() #преобразование тензора в массив Numpy
print(b2)

[1 2 3 4]


### Изменяемые тензоры

In [10]:
v1 = tf.Variable(-1.2)

In [11]:
v2 = tf.Variable([4, 5, 6, 7], dtype=tf.float32)

In [12]:
v3 = tf.Variable(b)

In [13]:
print(v1, v2, v3, sep="\n\n")

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-1.2>

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([4., 5., 6., 7.], dtype=float32)>

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>


In [14]:
v1.assign(0) #изменение значения тензора
print(v1)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>


In [15]:
v2.assign([0, 1, 6, 7])
print(v2)

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 1., 6., 7.], dtype=float32)>


In [16]:
v3.assign_add([1, 1, 1, 1])     #добавление значений
v1.assign_sub(5)                #вычитание значений

print(v1, v3, sep="\n")

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-5.0>
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>


In [17]:
v4 = tf.Variable(v1) #копия существующей переменной
print(v4)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-5.0>


In [18]:
print(v4.shape)

()


In [19]:
print(v2.shape)

(4,)


### Индексирование элементов тензоров

In [20]:
val_0 = v3[0]
val_12 = v3[1:3]

In [22]:
print(v3, val_0, val_12, sep="\n")

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)


#### Списочное индексирование

In [24]:
x = tf.constant(range(10)) + 5

x_indx = tf.gather(x, [0, 4])
print(x, x_indx, sep="\n")

tf.Tensor([ 5  6  7  8  9 10 11 12 13 14], shape=(10,), dtype=int32)
tf.Tensor([5 9], shape=(2,), dtype=int32)


In [26]:
v2 = tf.constant([[1, 2, 7], [3, 4, 8], [5, 6, 9]])
val_indx = v2[(1, 2)] #обращение к 1-строке и 2-столбцу

print(val_indx)

tf.Tensor(8, shape=(), dtype=int32)


In [27]:
val_indx = v2[:, 1] #столбец
print(val_indx) 

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [28]:
val_indx = v2[:2, 1]
print(val_indx) 

tf.Tensor([2 4], shape=(2,), dtype=int32)


In [29]:
val_indx = v2[:2, -1]
print(val_indx) 

tf.Tensor([7 8], shape=(2,), dtype=int32)


#### Изменение формы вектора

In [31]:
a = tf.constant(range(30))
print(a)

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


In [33]:
b = tf.reshape(a, [5 ,6])
print(b.numpy())

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [34]:
b = tf.reshape(a, [6 ,-1])
print(b.numpy())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [36]:
b_T = tf.transpose(b, perm=[1, 0]) #транспонирование тензора

print(b_T)

tf.Tensor(
[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]], shape=(5, 6), dtype=int32)
