# 3. Математические операции и функции над тензорами

In [1]:
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf
import numpy as np

2024-09-29 22:50:36.966705: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-29 22:50:36.977155: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-29 22:50:36.980186: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


#### Функции автозаполнения

In [3]:
a = tf.zeros((3, 3))
print(a)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [4]:
b = tf.ones((3, 5))
b

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [5]:
c = tf.ones_like(a)
c

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [6]:
c = tf.zeros_like(b)
c

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [7]:
d = tf.eye(3)
d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [8]:
d = tf.eye(3, 2)
d

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.]], dtype=float32)>

In [10]:
e = tf.identity(c) #копия тензора с сохранением значений
e

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [11]:
f = tf.fill((2, 3), -1)
f

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-1, -1, -1],
       [-1, -1, -1]], dtype=int32)>

In [12]:
g = tf.range(1, 11, 0.2)
g

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([ 1.       ,  1.2      ,  1.4      ,  1.6      ,  1.8      ,
        2.       ,  2.2      ,  2.4      ,  2.6      ,  2.8000002,
        3.       ,  3.2      ,  3.4      ,  3.6000001,  3.8      ,
        4.       ,  4.2      ,  4.4      ,  4.6000004,  4.8      ,
        5.       ,  5.2000003,  5.4      ,  5.6      ,  5.8      ,
        6.       ,  6.2000003,  6.4      ,  6.6      ,  6.8      ,
        7.       ,  7.2000003,  7.4      ,  7.6      ,  7.8      ,
        8.       ,  8.200001 ,  8.4      ,  8.6      ,  8.8      ,
        9.       ,  9.2      ,  9.400001 ,  9.6      ,  9.8      ,
       10.       , 10.2      , 10.400001 , 10.6      , 10.8      ],
      dtype=float32)>

#### Генерация случайных значений

In [15]:
a = tf.random.normal((2, 4), 0, 0.1)
a

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.10693945, -0.11885202, -0.03659537,  0.0817058 ],
       [-0.07199726, -0.08746328,  0.19782601, -0.05093456]],
      dtype=float32)>

In [18]:
b = tf.random.uniform((2, 2), -1, 1)
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.13482308,  0.01954842],
       [-0.01748466,  0.3690095 ]], dtype=float32)>

In [26]:
tf.random.set_seed(1)
d = tf.random.truncated_normal((1, 5), -1, 0.1)
d

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[-1.110122  , -0.84542483, -0.9616356 , -1.0879657 , -0.85944796]],
      dtype=float32)>

In [28]:
d = tf.random.truncated_normal((1, 5), -1, 0.1)
d

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[-1.0457013, -1.0406867, -0.9271422, -1.0892978, -1.0369405]],
      dtype=float32)>

In [25]:
tf.random.set_seed(1)
d = tf.random.truncated_normal((1, 5), -1, 0.1)
d

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[-1.110122  , -0.84542483, -0.9616356 , -1.0879657 , -0.85944796]],
      dtype=float32)>

In [33]:
a = tf.constant([1, 2, 3])
b = tf.constant([9, 8, 7])

In [34]:
tf.add(a, b) #сложение тензоров

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [35]:
a + b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [36]:
tf.subtract(a, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [37]:
tf.divide(a, b) #деление

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [38]:
a // b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [39]:
tf.multiply(a, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [40]:
a * b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [41]:
a ** 2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [42]:
tf.tensordot(a, b, axes=0) #внешнее векторное умножение

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9,  8,  7],
       [18, 16, 14],
       [27, 24, 21]], dtype=int32)>

In [43]:
tf.tensordot(a, b, axes=1) #внутренее умножение

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [44]:
a2 = tf.constant(tf.range(1, 10), shape=(3, 3))
b2 = tf.constant(tf.range(5, 14), shape=(3, 3))

In [46]:
tf.matmul(a2, b2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]], dtype=int32)>

In [47]:
a2 @ b2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]], dtype=int32)>

In [48]:
m = tf.tensordot(a, b, axes=0)
m

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9,  8,  7],
       [18, 16, 14],
       [27, 24, 21]], dtype=int32)>

In [49]:
tf.reduce_sum(m)

<tf.Tensor: shape=(), dtype=int32, numpy=144>

In [50]:
tf.reduce_sum(m, axis=0) #суммирование по столбцам

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([54, 48, 42], dtype=int32)>

In [51]:
tf.reduce_sum(m, axis=1) #суммирование по строкам

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([24, 48, 72], dtype=int32)>

In [52]:
tf.reduce_sum(m, axis=[0, 1]) #суммирование всех элементов

<tf.Tensor: shape=(), dtype=int32, numpy=144>

In [53]:
tf.reduce_mean(m) #среднее

<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [54]:
tf.reduce_max(m)

<tf.Tensor: shape=(), dtype=int32, numpy=27>

In [55]:
tf.reduce_max(m, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 18, 27], dtype=int32)>

In [56]:
tf.reduce_prod(m) #произведение всех элементво матрицы

<tf.Tensor: shape=(), dtype=int32, numpy=1883394048>

In [58]:
tf.reduce_prod(m, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4374, 3072, 2058], dtype=int32)>

In [59]:
tf.sqrt(tf.cast(a, dtype=tf.float32))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.       , 1.4142135, 1.7320508], dtype=float32)>

In [60]:
tf.square(a) #возведение поэлементно в квадрат

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [61]:
tf.sin(tf.range(-3.14, 3.14, 1))

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([-0.00159255, -0.8423304 , -0.90863353, -0.13954322,  0.7578425 ,
        0.9584713 ,  0.27788603], dtype=float32)>

In [62]:
tf.cos(tf.range(-3.14, 3.14, 1))

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([-0.99999875, -0.5389615 ,  0.4175944 ,  0.99021596,  0.65243757,
       -0.28518897, -0.960614  ], dtype=float32)>