# 3. Создание тензоров. Конвертирование в NumPy

In [4]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

2.4.1+cpu


In [9]:
t = torch.Tensor(3, 5, 2)

t

tensor([[[3.4329e-06, 1.0930e-05],
         [1.2993e-08, 2.3051e-12],
         [1.8788e+31, 7.9303e+34],
         [6.1949e-04, 1.8590e+34],
         [7.7767e+31, 7.1536e+22]],

        [[3.3803e-18, 2.0552e+32],
         [1.8755e+28, 3.1093e-18],
         [1.8692e+20, 2.8638e+20],
         [3.2850e-18, 1.2845e+31],
         [1.8395e+25, 6.1963e-04]],

        [[5.3461e+22, 6.8989e-07],
         [3.1984e+21, 8.3016e-10],
         [1.6596e-07, 4.2231e-08],
         [2.6586e+23, 2.6542e+20],
         [2.4288e-18, 1.1963e+22]]])

In [10]:
t.dtype

torch.float32

In [ ]:
#тензор

t = torch.empty(3, 5, 2)

t.dtype

torch.float32

In [12]:
t = torch.empty(3, 5, 2, dtype=torch.int32)
t.dtype

torch.int32

In [13]:
torch.tensor([1])

tensor([1])

In [14]:
torch.tensor([1, 2, 0])

tensor([1, 2, 0])

In [15]:
torch.tensor([[1, 2], [3, 4], [5, 6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
torch.tensor([1, 2.0]) #вещественный тип данных

tensor([1., 2.])

In [17]:
torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [18]:
torch.tensor([[1, 2], [3, 4], [5]])

ValueError: expected sequence of length 2 at dim 1 (got 1)

In [19]:
torch.IntTensor([1]) #применение класса для создания тезора с нужным типом данных


tensor([1], dtype=torch.int32)

In [20]:
torch.ByteTensor([[1, 2], [3, 4], [5, 6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.uint8)

In [22]:
t = torch.DoubleTensor(3, 2, 3, 5)
t

tensor([[[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00, 6.2380e-310],
          [6.2380e-310,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  

In [24]:
#создание тензора
d = [[[1, 2, 3], [3, 4, 5]]]
t = torch.tensor(d, dtype=torch.float32)
t

tensor([[[1., 2., 3.],
         [3., 4., 5.]]])

In [25]:
t.type()

'torch.FloatTensor'

In [27]:
t.dtype

torch.float32

In [28]:
t.dim() #количество осей

3

In [29]:
t.size()

torch.Size([1, 2, 3])

In [30]:
t.shape

torch.Size([1, 2, 3])

In [50]:
d_np = np.array([[1, 2, 3], [4, 5, 6]])
d_np

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
#создание тензора из массива numpy

t2 = torch.from_numpy(d_np)
t2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [52]:
#создание тензора из массива numpy

t3 = torch.tensor(d_np, dtype=torch.float32)
t3

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [53]:
d_np[0, 0] = 5

t2

tensor([[5, 2, 3],
        [4, 5, 6]])

In [54]:
t3

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [55]:
t3 = torch.tensor(d_np)
t3

tensor([[5, 2, 3],
        [4, 5, 6]])

In [56]:
t3[0, 0] = 1
d_np

array([[5, 2, 3],
       [4, 5, 6]])

In [58]:
# тензоры на основе списка

d = [[1, 2, 3], [4, 5, 6]]
t = torch.IntTensor(d)
tt = torch.tensor(d)
tt

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#из тензора в numpy

d = t2.numpy() #копирование не происходит
d

array([[5, 2, 3],
       [4, 5, 6]])

In [61]:
t2.dtype

torch.int64

In [63]:
#преобразование типа данных тензора

tf = t2.float()
tf.dtype

torch.float32

In [64]:
t = torch.tensor([1, 2, 3])
t.dtype

torch.int64

In [65]:
t2 = t.long()
t2.dtype

torch.int64