# 4. Тензоры. Автозаполнение, изменение формы

In [3]:
import torch
import numpy as np

In [4]:
tz = torch.zeros(2, 3)
tz

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
tz = torch.zeros(2, 3, dtype=torch.int32)
tz

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [7]:
to = torch.ones(2, 3)
to

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
to = torch.ones(2, 3, dtype=torch.long)
to

tensor([[1, 1, 1],
        [1, 1, 1]])

In [10]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
torch.eye(3, 2)

tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])

In [13]:
t = torch.full((2, 4), 5)
t

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5]])

In [14]:
torch.arange(7)

tensor([0, 1, 2, 3, 4, 5, 6])

In [15]:
torch.arange(-5, 0)

tensor([-5, -4, -3, -2, -1])

In [16]:
torch.arange(-5, 0, 2)

tensor([-5, -3, -1])

In [18]:
torch.arange(1, 0, -0.2)

tensor([1.0000, 0.8000, 0.6000, 0.4000, 0.2000])

In [19]:
torch.linspace(1, 5, 2)

tensor([1., 5.])

In [20]:
torch.linspace(1, 5, 3)

tensor([1., 3., 5.])

In [21]:
torch.linspace(1, 5, 5)

tensor([1., 2., 3., 4., 5.])

In [ ]:
torch.rand(2, 3) #тензор со случайными значениями с равномерным рапределением

tensor([[0.4842, 0.8151, 0.0616],
        [0.3697, 0.0513, 0.9537]])

In [ ]:
torch.randn(2, 3) #тензор со случайными значениями с нормальным рапределением

tensor([[ 0.7448,  0.1038,  0.0708],
        [-0.9160,  0.5298, -0.5509]])

In [31]:
torch.manual_seed(12)
torch.randn(2, 3)

tensor([[-0.2138, -1.3780, -0.0546],
        [ 0.4515,  0.7858, -1.0884]])

In [26]:
torch.manual_seed(12)
torch.randn(7, 2)

tensor([[-0.2138, -1.3780],
        [-0.0546,  0.4515],
        [ 0.7858, -1.0884],
        [-0.5599, -0.9336],
        [ 0.0479, -0.0844],
        [-0.1471,  0.7590],
        [ 0.1466, -1.0041]])

In [32]:
x = torch.FloatTensor(2, 4)
x

tensor([[1.1175e+30, 4.2689e-41, 1.1175e+30, 4.2689e-41],
        [3.4473e-07, 4.2689e-41, 1.2543e-38, 0.0000e+00]])

In [ ]:
x.fill_(1) #замена тензора
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
x.fill_(-0.3)
x

tensor([[-0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000, -0.3000, -0.3000]])

In [35]:
x.random_(1, 7)
x

tensor([[5., 6., 4., 4.],
        [5., 2., 5., 1.]])

In [ ]:
x.uniform_(0, 1) #заполнение непрерывными значениями
x

tensor([[0.6601, 0.0554, 0.1573, 0.8137],
        [0.7216, 0.2717, 0.3003, 0.6099]])

In [ ]:
x.normal_(0, 1) #заполнение гауссовскими значениями
x

tensor([[-0.7882, -0.8074, -0.2957, -0.1462],
        [ 0.3641,  0.4331,  0.5895, -1.2568]])

In [38]:
x = torch.FloatTensor(2, 4).zero_()
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
x = torch.FloatTensor(2, 4).fill_(10)
x

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.]])

представление разных тензоров

In [40]:
x = torch.arange(27)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
d = x.view(3, 9) #изменине представление тензора
d

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [42]:
x[0] = 100
x

tensor([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26])

In [43]:
d

tensor([[100,   1,   2,   3,   4,   5,   6,   7,   8],
        [  9,  10,  11,  12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [44]:
r = x.reshape(3, 3, 3)
r

tensor([[[100,   1,   2],
         [  3,   4,   5],
         [  6,   7,   8]],

        [[  9,  10,  11],
         [ 12,  13,  14],
         [ 15,  16,  17]],

        [[ 18,  19,  20],
         [ 21,  22,  23],
         [ 24,  25,  26]]])

In [45]:
x.resize_(2, 3) #новое представление


tensor([[100,   1,   2],
        [  3,   4,   5]])

In [ ]:
x.ravel() #вытягивание в один вектор

tensor([100,   1,   2,   3,   4,   5])

In [47]:
d

tensor([[100,   1,   2,   3,   4,   5,   6,   7,   8],
        [  9,  10,  11,  12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [48]:
d.permute(1, 0) #изменине осей местами

tensor([[100,   9,  18],
        [  1,  10,  19],
        [  2,  11,  20],
        [  3,  12,  21],
        [  4,  13,  22],
        [  5,  14,  23],
        [  6,  15,  24],
        [  7,  16,  25],
        [  8,  17,  26]])

In [ ]:
d.mT # транспонирование

tensor([[100,   9,  18],
        [  1,  10,  19],
        [  2,  11,  20],
        [  3,  12,  21],
        [  4,  13,  22],
        [  5,  14,  23],
        [  6,  15,  24],
        [  7,  16,  25],
        [  8,  17,  26]])

In [51]:
#изменение количества осей

x_test = torch.arange(32).view(8, 2, 2)
x_test.size()

torch.Size([8, 2, 2])

In [ ]:
x_test4 = torch.unsqueeze(x_test, dim=0) #добавление оси 
x_test4.size()

torch.Size([1, 8, 2, 2])

In [55]:
r = x_test.unsqueeze(0)
r.size()

torch.Size([1, 8, 2, 2])

In [56]:
x_test.unsqueeze_(0)
x_test.size()

torch.Size([1, 8, 2, 2])

In [ ]:
b = torch.unsqueeze(x_test4, dim=-1) #добавлние еще одной оси в конце
b.size()

torch.Size([1, 8, 2, 2, 1])

In [58]:
#удаление осей

c = torch.squeeze(b)
c.size()

torch.Size([8, 2, 2])

In [59]:
c = torch.squeeze(b, dim=0)
c.size()

torch.Size([8, 2, 2, 1])