# 5. Тензоры. Индексирование и срезы

In [1]:
import torch
import numpy as np

In [3]:
a = torch.arange(12)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
a[2]

tensor(2)

In [5]:
#число
a[2].item()

2

In [6]:
a[-1]

tensor(11)

In [7]:
a[-2]

tensor(10)

In [8]:
a[0] = 100
a

tensor([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [9]:
#срез (представление тензора)
b = a[2:4]
b

tensor([2, 3])

In [10]:
b[0] = -100
b

tensor([-100,    3])

In [11]:
a

tensor([ 100,    1, -100,    3,    4,    5,    6,    7,    8,    9,   10,   11])

In [12]:
a[3:]

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
a[:5]

tensor([ 100,    1, -100,    3,    4])

In [14]:
a[-5: -1]

tensor([ 7,  8,  9, 10])

In [15]:
#полный срез
a[:]

tensor([ 100,    1, -100,    3,    4,    5,    6,    7,    8,    9,   10,   11])

In [16]:
a[1:6:2] #старт, стоп, степ

tensor([1, 3, 5])

In [17]:
a[::2] #все элементы с шагом 2

tensor([ 100, -100,    4,    6,    8,   10])

In [18]:
#внесение новых значений

a[:4] = torch.IntTensor([-1, -2, -3, 4])
a

tensor([-1, -2, -3,  4,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
x = torch.IntTensor([(1, 2, 3), (10, 20, 30), (100, 200, 300)])
x

tensor([[  1,   2,   3],
        [ 10,  20,  30],
        [100, 200, 300]], dtype=torch.int32)

In [20]:
x[1, 1]

tensor(20, dtype=torch.int32)

In [21]:
x[-1, -1]

tensor(300, dtype=torch.int32)

In [22]:
x[0] #1 строка

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
x[:, 1] # 2й столбец

tensor([  2,  20, 200], dtype=torch.int32)

In [26]:
a = torch.arange(1, 82).view(3, 3, 3, 3)
a

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],

         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]],


        [[[28, 29, 30],
          [31, 32, 33],
          [34, 35, 36]],

         [[37, 38, 39],
          [40, 41, 42],
          [43, 44, 45]],

         [[46, 47, 48],
          [49, 50, 51],
          [52, 53, 54]]],


        [[[55, 56, 57],
          [58, 59, 60],
          [61, 62, 63]],

         [[64, 65, 66],
          [67, 68, 69],
          [70, 71, 72]],

         [[73, 74, 75],
          [76, 77, 78],
          [79, 80, 81]]]])

In [27]:
a[1, 2, 0, 1]

tensor(47)

In [28]:
#многомерный срез

a[:, 1, :, : ]

tensor([[[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]],

        [[64, 65, 66],
         [67, 68, 69],
         [70, 71, 72]]])

In [29]:
a[0, 0] # a[0, 0, :, :]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [30]:
a[:, :, 1, 1]

tensor([[ 5, 14, 23],
        [32, 41, 50],
        [59, 68, 77]])

In [31]:
a[0:2, 0:2, 1, 1]

tensor([[ 5, 14],
        [32, 41]])

In [32]:
a[..., 1, 1]

tensor([[ 5, 14, 23],
        [32, 41, 50],
        [59, 68, 77]])

In [33]:
a = torch.arange(1, 9)
a

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
a[0]

tensor(1)

In [35]:
a[0].item()

1

In [36]:
a[[0]] #тензор из первого элемента

tensor([1])

In [37]:
b = a[[0]]
b.size()

torch.Size([1])

In [38]:
b[0] = 100
a

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
b

tensor([100])

In [40]:
b = a[[0, 1, 7, 5]]
b

tensor([1, 2, 8, 6])

In [42]:
a[[0, 0, 1, 1, 1, 2, 3, 4, 5, 6, 7]]

tensor([1, 1, 2, 2, 2, 3, 4, 5, 6, 7, 8])

In [43]:
indx = torch.IntTensor([0, 0, 1, 1, 1, 2])
a[indx]

tensor([1, 1, 2, 2, 2, 3])

In [44]:
bIndex = torch.BoolTensor([True, True, False, False, False, True, False, False])

In [45]:
a[bIndex]

tensor([1, 2, 6])

In [47]:
i = a > 5
i

tensor([False, False, False, False, False,  True,  True,  True])

In [48]:
a[i]

tensor([6, 7, 8])

In [49]:
a[a > 5]

tensor([6, 7, 8])