# 6. Тензоры. Базовые математические операции

In [1]:
import torch
import numpy as np

In [2]:
a = torch.FloatTensor([1, 2, 3])

In [3]:
a - 3

tensor([-2., -1.,  0.])

In [4]:
-a

tensor([-1., -2., -3.])

In [5]:
2 + a

tensor([3., 4., 5.])

In [6]:
a * 5

tensor([ 5., 10., 15.])

In [7]:
a / 5

tensor([0.2000, 0.4000, 0.6000])

In [8]:
a ** 3

tensor([ 1.,  8., 27.])

In [9]:
a // 2

tensor([0., 1., 1.])

In [10]:
a % 2

tensor([1., 0., 1.])

In [12]:
b = torch.IntTensor([3, 4, 5])
b

tensor([3, 4, 5], dtype=torch.int32)

In [13]:
a - b

tensor([-2., -2., -2.])

In [14]:
b + a

tensor([4., 6., 8.])

In [15]:
b / a

tensor([3.0000, 2.0000, 1.6667])

In [16]:
b // a

tensor([3., 2., 1.])

In [17]:
b ** a

tensor([  3.,  16., 125.])

In [18]:
b % a

tensor([0., 0., 2.])

In [19]:
b = torch.IntTensor([3, 4, 5, 6])

In [20]:
b = torch.arange(1, 7).view(2, 3)
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
a + b

tensor([[2., 4., 6.],
        [5., 7., 9.]])

In [22]:
a = torch.arange(1, 19).view(3, 3, 2)
b = torch.ones(3, 2)

In [23]:
a - b

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.]],

        [[ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]],

        [[12., 13.],
         [14., 15.],
         [16., 17.]]])

In [24]:
a * 10

tensor([[[ 10,  20],
         [ 30,  40],
         [ 50,  60]],

        [[ 70,  80],
         [ 90, 100],
         [110, 120]],

        [[130, 140],
         [150, 160],
         [170, 180]]])

In [25]:
a // b

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.],
         [17., 18.]]])

In [26]:
a = torch.IntTensor([1, 2, 6, 8])
a

tensor([1, 2, 6, 8], dtype=torch.int32)

In [27]:
a += 5
a

tensor([ 6,  7, 11, 13], dtype=torch.int32)

In [28]:
b = torch.ones(4)
b

tensor([1., 1., 1., 1.])

In [29]:
b * a

tensor([ 6.,  7., 11., 13.])

In [30]:
(a + b) * 5 - 10

tensor([25., 30., 50., 60.])

In [31]:
a = torch.arange(5, dtype=torch.float32)
b = torch.ones(5)


In [32]:
r = a.add(b) #сумма тензоров, без замены
r

tensor([1., 2., 3., 4., 5.])

In [33]:
r = a.add_(b) #метод с заменой
r

tensor([1., 2., 3., 4., 5.])

In [34]:
a

tensor([1., 2., 3., 4., 5.])

In [35]:
r = a.mul_(5)
r

tensor([ 5., 10., 15., 20., 25.])

In [36]:
r = a.sub_(b) - 2 #формируется новый тензор
r

tensor([ 2.,  7., 12., 17., 22.])