# 7. Тензоры. Тригонометрические и статистические функции

In [1]:
import torch
import numpy as np

# Базовые математические функции

In [2]:
a = torch.FloatTensor([1, 2, 3, 10, 20, 30])

In [4]:
a.sum().item()

66.0

In [5]:
a.mean()

tensor(11.)

In [6]:
a.max()

tensor(30.)

In [7]:
a.min()

tensor(1.)

In [9]:
a = a.view(3, 2)
a

tensor([[ 1.,  2.],
        [ 3., 10.],
        [20., 30.]])

In [10]:
a.sum() #сумма всех элементов

tensor(66.)

In [11]:
a.sum(dim=0) #суммирование по столбцам

tensor([24., 42.])

In [12]:
a.sum(dim=1) #сумма по строкам

tensor([ 3., 13., 50.])

In [13]:
a.max(dim=1)

torch.return_types.max(
values=tensor([ 2., 10., 30.]),
indices=tensor([1, 1, 1]))

In [14]:
a.max(dim=1).values

tensor([ 2., 10., 30.])

In [15]:
a.amax(dim=1)

tensor([ 2., 10., 30.])

In [16]:
a.amin(dim=0)

tensor([1., 2.])

In [17]:
a = torch.IntTensor([-1, 1, 5, -44, 32, 2])
a

tensor([ -1,   1,   5, -44,  32,   2], dtype=torch.int32)

In [18]:
torch.abs(a) #модуль

tensor([ 1,  1,  5, 44, 32,  2], dtype=torch.int32)

In [19]:
a.abs_()
a

tensor([ 1,  1,  5, 44, 32,  2], dtype=torch.int32)

In [20]:
a = torch.IntTensor([-1, 1, 5, -44, 32, 2])

In [21]:
torch.amax(a)

tensor(32, dtype=torch.int32)

In [22]:
torch.log(a)

tensor([   nan, 0.0000, 1.6094,    nan, 3.4657, 0.6931])

In [23]:
a = a.float()
a

tensor([ -1.,   1.,   5., -44.,  32.,   2.])

In [24]:
a.log_()

tensor([   nan, 0.0000, 1.6094,    nan, 3.4657, 0.6931])

In [25]:
a = torch.FloatTensor([-1.5, 1.2, 5.8, -44, 32, 2])
a

tensor([ -1.5000,   1.2000,   5.8000, -44.0000,  32.0000,   2.0000])

In [26]:
a.round_() #округление

tensor([ -2.,   1.,   6., -44.,  32.,   2.])

# Тригонометрические функции

In [27]:
a = torch.linspace(0, torch.pi, 10) #интревал от 0 до Пи разделенный на 10 рисок
a

tensor([0.0000, 0.3491, 0.6981, 1.0472, 1.3963, 1.7453, 2.0944, 2.4435, 2.7925,
        3.1416])

In [29]:
r = torch.sin(a)
r

tensor([ 0.0000e+00,  3.4202e-01,  6.4279e-01,  8.6603e-01,  9.8481e-01,
         9.8481e-01,  8.6603e-01,  6.4279e-01,  3.4202e-01, -8.7423e-08])

In [30]:
r = a.cos()
r

tensor([ 1.0000,  0.9397,  0.7660,  0.5000,  0.1736, -0.1736, -0.5000, -0.7660,
        -0.9397, -1.0000])

In [31]:
a.tan_()

tensor([ 0.0000e+00,  3.6397e-01,  8.3910e-01,  1.7321e+00,  5.6713e+00,
        -5.6713e+00, -1.7321e+00, -8.3910e-01, -3.6397e-01,  8.7423e-08])

# Статистические функции

In [32]:
x = torch.FloatTensor([1, 4, 3, 7, 10, 8, 14, 21, 20, 23])
y = torch.FloatTensor([4, 1, 6, 9, 13, 11, 16, 19, 15, 22])

In [33]:
torch.median(x)

tensor(8.)

In [34]:
x.var() #дисперсия

tensor(63.6556)

In [35]:
y.std()

tensor(6.7032)

In [36]:
xy = torch.vstack([x, y])
xy

tensor([[ 1.,  4.,  3.,  7., 10.,  8., 14., 21., 20., 23.],
        [ 4.,  1.,  6.,  9., 13., 11., 16., 19., 15., 22.]])

In [37]:
torch.corrcoef(xy)

tensor([[1.0000, 0.9316],
        [0.9316, 1.0000]])

In [38]:
torch.cov(xy)

tensor([[63.6556, 49.8222],
        [49.8222, 44.9333]])