# 8. Тензоры. Векторно-матричные операции

In [1]:
import torch
import numpy as np

In [2]:
a = torch.arange(1, 10).view(3, 3)
b = torch.arange(10, 19).view(3, 3)

In [3]:
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
b

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [5]:
r1 = a * b #умножение 
r1

tensor([[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]])

In [6]:
r2 = a.mul(b)
r2

tensor([[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]])

In [7]:
#матричное умножение

c = torch.matmul(a, b) #с возможностью транслирования
c

tensor([[ 84,  90,  96],
        [201, 216, 231],
        [318, 342, 366]])

In [8]:
c = torch.mm(a, b) #без возможности транслирования
c

tensor([[ 84,  90,  96],
        [201, 216, 231],
        [318, 342, 366]])

In [9]:
v = torch.LongTensor([-1, -2, -3])
v

tensor([-1, -2, -3])

In [11]:
c = torch.matmul(a, v) #умножение матрицы на вектор
c

tensor([-14, -32, -50])

In [12]:
c = torch.matmul(v, a) #умножение матрицы на вектор
c

tensor([-30, -36, -42])

In [13]:
c = torch.mm(v, a) #ошибка так как векторы не согласованы по размеру
c

RuntimeError: self must be a matrix

In [14]:
c = a.mm(b)
c

tensor([[ 84,  90,  96],
        [201, 216, 231],
        [318, 342, 366]])

In [16]:
c = a.matmul(b)
c

tensor([[ 84,  90,  96],
        [201, 216, 231],
        [318, 342, 366]])

In [17]:
bx = torch.randn(7, 3, 5)
by = torch.randn(7, 5, 4)

In [18]:
bc = torch.bmm(bx, by) #умножение группы матриц
bc.size()

torch.Size([7, 3, 4])

In [19]:
bc

tensor([[[-2.0324,  4.2145,  3.2254, -2.3593],
         [-1.5980,  4.0208, -0.0453, -0.3672],
         [-0.0901,  0.8998, -0.6926, -0.2185]],

        [[ 0.9651,  1.0686, -0.4136, -3.0964],
         [-1.8691, -1.8890,  0.0393, -0.2195],
         [-0.9142, -2.1295,  1.1452,  3.1222]],

        [[ 8.9970, -3.0013,  5.0281, -4.7680],
         [ 1.2037,  5.0938,  2.3802, -0.6707],
         [ 3.2941, -1.6341,  4.7993, -4.0292]],

        [[ 1.4433,  0.4030, -0.8282, -0.2687],
         [ 1.0755, -1.9602,  2.4024, -0.7519],
         [-2.2605, -1.1770,  0.0363,  1.9147]],

        [[ 0.3320, -0.3438, -0.9324, -0.2072],
         [ 2.2118, -2.0535, -1.0854, -1.3640],
         [ 2.1864,  1.2041, -1.3564,  3.6402]],

        [[-1.1985,  1.6026,  1.2574,  2.4660],
         [ 2.2954, -1.0462, -2.9878, -0.7202],
         [ 2.4607,  2.0292, -2.1783,  4.4320]],

        [[-1.1061, -1.0880,  2.1220, -1.1052],
         [-1.7394,  0.2291, -1.6031,  3.0674],
         [ 1.4957,  1.4060, -0.4606, -1.8913]]])

In [20]:
a = torch.arange(1, 10, dtype=torch.float32)
b = torch.ones(9)

In [21]:
a

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
c = torch.dot(a, b) #скалярное произведение
c

tensor(45.)

In [23]:
c = torch.outer(a, b)
c

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [24]:
a = torch.FloatTensor([1, 2, 3]) #вектор
b = torch.arange(4, 10, dtype=torch.float32).view(2, 3) #матрица

In [25]:
r = torch.mv(b, a) #умножение матрицы на вектор
r

tensor([32., 50.])

In [26]:
r = b.mv(a) #первым аргументом должна быть матрица
r

tensor([32., 50.])

In [27]:
a = torch.FloatTensor([(1, 2, 3), (1, 4, 9), (1, 8, 27)])
a

tensor([[ 1.,  2.,  3.],
        [ 1.,  4.,  9.],
        [ 1.,  8., 27.]])

In [28]:
torch.linalg.matrix_rank(a)

tensor(3)

In [29]:
y = torch.FloatTensor([10, 20, 30])

In [30]:
torch.linalg.solve(a, y) #вычисление коэффициентов х1, х2 и х3 в системе линейных уравнений

tensor([-5.0000, 10.0000, -1.6667])

In [31]:
invA = torch.linalg.inv(a)

In [33]:
x = torch.mv(invA, y) #вычисление через обратную матрицу
x

tensor([-5.0000, 10.0000, -1.6667])