# 13. Функции активации и потерь в PyTorch

In [1]:
import torch
import numpy as np
from random import randint
import matplotlib.pyplot as plt

In [2]:
#импорт функций активации

import torch.nn.functional as F 

F.linear() # только для выходных слоев в регрессиях

F.sigmoid() # для бинарной классификации

F.softmax() # для бинарной классификации


#импорт функций потерь

torch.nn.MSELoss

# 14. Автоматическое дифференцирование

In [3]:
#создание тензоров

x = torch.tensor([2.0], requires_grad=True)
y = torch.tensor([-4.0], requires_grad=True)

#f = (x + y) ** 2 + 2 * x * y

a = (x + y) ** 2
b = 2 * x * y
f = a + b

f.backward()

print(f)
print(x.data, x.grad)
print(y.data, y.grad)

tensor([-12.], grad_fn=<AddBackward0>)
tensor([2.]) tensor([-12.])
tensor([-4.]) tensor([0.])
